<div class="inner_con bg_grey">
	<div class="wraper fc_black">
	<h2 class="fw600 mart15 marb15 titel">Terms of Use</h2>
    
<p>
PLEASE READ THE FOLLOWING TERMS OF USE CAREFULLY BEFORE USING THE Jockdrive WEBSITE (THE "SITE"). If you are browsing through the Site and have not yet registered to become a member, your use of the Site is still subject to the Terms of Use; if you do not agree to the Terms of Use, please do not use the Website. 
</p>
<ol>
    <li><h3><strong>Agreement to Terms of Use</strong></h3><br>
    By using this Site, you signify that you agree to these Terms of Use. In addition, when using particular services available on this Site, you will be subject to any posted guidelines or rules applicable to such services that may be posted from time to time. We reserve the right, at our discretion, to change, modify, add, or remove portions of these Terms of Use at any time. Please check these Terms of Use periodically for changes. Your continued use of this Site after the posting of changes will mean you agree to abide by those changes. 
    </li>
    <li><h3><strong>Ownership</strong></h3><br>
    This Site is owned and operated by Jockdrive. The information, data, text, software, music, sound, photographs, graphics, video, messages and other information and material (collectively, "Content") of this Site is protected by United States copyright and trademark law, international conventions and other applicable laws. This Site, except for User Content as specified below, is the copyrighted property of Jockdrive. You have no right to use, copy, display, perform, create derivative works from, distribute, have distributed, transmit, or sublicense Content on this Site, except as expressly set forth in these Terms of Use; the sale, auction, lease, loan, gift, trade or barter, or use of any of the Content for any other purpose, in any form, media or technology now known or hereafter developed, including the use of any of the Content on any other Website or networked computer environment, except for your own User Content, is expressly prohibited. The creation of derivative works based on the Content, except for your own User Content, (whether sold, bartered or given away) is expressly prohibited. 
    </li>
    <li><h3><strong>Registered Users</strong></h3><br>
    When you register for an account on the Site we may ask you to provide us with certain personal information about yourself including, without limitation, your name, address, telephone number, email or other electronic address, professional affiliations, photographs, and other biographical information (collectively, "Your Information"). 
    Once you are a registered user, you may provide additional information in your personal profile describing your biographical background. Your personal profile may be available for viewing by other registered users and as such, is not confidential and is not proprietary to you. Providing additional information in your personal profile is optional. 
    Please review our Privacy Policy for clarification on how we may use Your Information and other information that you may provide or submit while using the Site. For your part, you agree that all Your Information that you provide to us is complete, accurate and up to date. You will notify us of any changes to Your Information. If you fail to update Your Information or if all or part of Your Information is (or appears to be) untrue, inaccurate, or incomplete we may suspend or terminate your membership and refuse any and all current or future use of our Site. You are solely responsible for the activity that occurs on your account, and you must keep your account password secure. You must notify us immediately of any breach of security or unauthorized use of your account. You may never use another's account without permission. Children under the age of 16 are not authorized to be registered users of the Site.
    </li>
    <li><h3><strong>Site Services</strong></h3><br>
    This Site allows registered users to publish information and comments, and comment on the information or comments of other users (the "Information Services") and allows registered users to upload and publish audio and other multimedia files, and comment on those files uploaded by other users (the "Multimedia Services). The Information Services and Multimedia Services are collectively referred to as the "Site Services". All information, comments, audio, visual, audiovisual, and other multimedia files, and related comments uploaded or published by you or a third party through the Site Services are collectively referred to as "User Content."
    </li>
    <li><h3><strong>Conditions on Use of the Site Services</strong></h3><br>
    You may access and use the Site and the Site Services as set forth in these Terms of Use, subject to the following conditions: 
    <ol type="a">
        <li>You are responsible for your own use of the Site, for any User Content you publish, and for any consequences thereof. You will use the Site in compliance with these Terms of Use and all applicable local, state, national, and international laws, rules and regulations.</li>
        <li>You affirm, represent, and warrant that you own or have the necessary licenses, rights, consents, and permissions to use and authorize Jockdrive to use all patent, trademark, trade secret, copyright or other proprietary rights in and to any and all User Content that you publish or upload to enable inclusion and use of that User Content in the manner contemplated by the Site and these Terms of Use.</li>
        <li>You may not distribute in any medium any part of the Site.</li>
        <li>You may not access Content, including User Content, through any technology or means other than the playback pages of the Site or other explicitly authorized means Jockdrive may designate.</li>
        <li>You may not collect or harvest any personally identifiable information, including account names, from the Site, nor to use the communication systems provided by the Site for any commercial solicitation purposes.</li>
        <li>You may not impersonate others or assume any false identity through our Site in a manner that is intended to or does mislead or confuse others.</li>
        <li>You may not use our Site or the Site Services for unlawful purposes or for promotion of dangerous or illegal activities.</li>
        <li>You may not spam or transmit malware or viruses.</li>
        <li>You may not use the Site or Site Services for any commercial use.</li>
        <li>You may not use or launch any automated system, including without limitation, "robots," "spiders," or "offline readers," that accesses the Site in a manner that sends more request messages to Jockdrive servers in a given period of time than a human can reasonably produce in the same period by using a conventional on-line web browser. Notwithstanding the foregoing, Jockdrive grants the operators of public search engines permission to use spiders to copy materials from the site for the sole purpose of and solely to the extent necessary for creating publicly available searchable indices of the materials, but not caches or archives of such materials. Jockdrive reserves the right to revoke these exceptions either generally or in specific cases.</li>
        <li>You may not use this Site in any manner that could damage, disable, overburden, or impair any Site or interfere with any other party's use and enjoyment of any Site.</li>
        <li>You may not attempt to gain unauthorized access to any Site, other accounts, computer systems or networks connected to any Site, through hacking, password mining or any other means.</li>
        <li>You may not obtain or attempt to obtain any materials or information through any means not intentionally made available through this Site.</li>
    </ol>
    </li>
    <li><h3><strong>User Content</strong></h3><br>
        <ol type="a">
            <li>Jockdrive claims no ownership or control over any User Content that you upload or publish. You or a third party licensor, as appropriate, retain all patent, trademark and copyright to any User Content you upload or publish and you are responsible for protecting those rights, as appropriate. By uploading or publishing User Content, you grant to Jockdrive a worldwide, perpetual, irrevocable non-exclusive, royalty-free, sublicensable and transferable license to reproduce, publish and distribute such User Content on our Site, any other website owned by Jockdrive, or any other website that Jockdrive chooses. Jockdrive reserves the right to delete, remove, and refuse to accept, post, display, or transmit any User Content in our sole discretion. Your User Content is not confidential and Jockdrive has no obligation as to maintaining the confidentiality of any User Content, including your direct correspondence to the Jockdrive.</li>
            <li>User Content is not provided by us. We have no obligation to monitor User Content and we take no responsibility for the User Content. We provide access to the User Content as an optional service to you.</li>
            <li>User Content may carry offensive, harmful, inaccurate or otherwise inappropriate material, or in some cases, postings that have been mislabeled or are otherwise deceptive. We expect that you will use caution and common sense and exercise proper judgment when viewing such User Content. We do not endorse, support, represent or guarantee the truthfulness, accuracy, or reliability of any User Content. You acknowledge that any reliance on User Content will be at your own risk and you agree to waive, and hereby do waive, any legal or equitable rights or remedies you have or may have against Jockdrive with respect thereto.</li>
            <li>You agree to not engage in the use, copying, or distribution of any of the User Content other than expressly permitted herein, including any use, copying, or distribution of User Content of third parties obtained through the Website for any commercial purposes.</li>
            <li>You agree not to circumvent, disable or otherwise interfere with security-related features of the Site or Site Services that prevent or restrict use or copying of any Content, including User Content.</li>
            <li>You will not upload or publish any User Content that:
                <ol>
                    <li>is copyrighted, protected by trade secret or otherwise subject to third party proprietary rights, including privacy and publicity rights, unless you are the owner of such rights or have permission from their rightful owner or are permitted by law to post the material and to grant Jockdrive all of the license rights granted herein.</li>
                    <li>is pornographic or obscene, or that promotes pedophilia, incest, or bestiality.</li>
                    <li>promotes hate toward groups based on race or ethnic origin, religion, disability, gender, age, veteran status, sexual orientation, or gender identity.</li>
                    <li>contains or promotes direct threats of violence against any person or group of people.</li>
                </ol>
            </li>
        </ol>
    </li>
    <li><h3><strong>Termination Policy</strong></h3><br>
    We reserve the right to decide whether User Content is appropriate and complies with these Terms of Use for violations other than copyright infringement, such as, but not limited to, pornography, obscene or defamatory material, or excessive length. We may remove such User Content or terminate a registered user's account at any time, without prior notice and at our sole discretion.
    Cause for termination includes, without limitation, breaches or violations of these Terms of Use or other Site guidelines, requests by law enforcement or other government agencies, a request by you, unexpected technical or security issues or problems, and extended periods of inactivity. You agree that any termination of your access to this Site or the Site Services or any portion thereof may be effected without prior notice, and you agree that Jockdrive is not be liable to you or any third-party for any such termination. 
    Jockdrive may in its sole discretion and at any time discontinue providing access to this Site or the Site Services, or any part thereof, with or without notice.
    </li>
    <li><h3><strong>Digital Millennium Copyright Act</strong></h3><br>
        <ol>
            <li>Notice. If you are a copyright owner or an agent thereof and believe that any User Content or other content infringes upon your copyrights, you may submit a notification pursuant to the Digital Millennium Copyright Act ("DMCA") by providing our Copyright Agent with the following information in writing (see 17 U.S.C 512(c)(3) for further detail):
                <ol type="i">
                    <li>A physical or electronic signature of a person authorized to act on behalf of the owner of an exclusive right that is allegedly infringed;</li>
                    <li>Identification of the copyrighted work claimed to have been infringed, or, if multiple copyrighted works at a single online site are covered by a single notification, a representative list of such works at that site;</li>
                    <li>Identification of the material that is claimed to be infringing or to be the subject of infringing activity and that is to be removed or access to which is to be disabled and information reasonably sufficient to permit the service provider to locate the material;</li>
                    <li>Information reasonably sufficient to permit the service provider to contact you, such as an address, telephone number, and, if available, an electronic mail;</li>
                    <li>A statement that you have a good faith belief that use of the material in the manner complained of is not authorized by the copyright owner, its agent, or the law; and</li>
                    <li>A statement that the information in the notification is accurate, and under penalty of perjury, that you are authorized to act on behalf of the owner of an exclusive right that is allegedly infringed.</li>
                </ol>
            </li>
            <li>Copyright Agent. The contact information for our designated Copyright Agent to receive notifications of claimed infringement is: (name, address, telephone, fax, email address). You acknowledge that if you fail to comply with all of the requirements of this Section 5(D), your DMCA notice may not be valid.</li>
            <li>Investigation and Response. Once our Copyright Agent receives a valid DMCA Copyright Claim Notice alleging that infringing materials are being distributed by the Site, we will use reasonable efforts to investigate the complaint in a timely manner and respond to the complaint. Our investigation may involve communication with the registered user accused of uploading or publishing the infringing material and evaluation of a counter-notice submitted by that registered user, if applicable. Our response may include removing the alleged infringing material or disabling access to that material.</li>
            <li>Counter-Notice. If you believe that your User Content that was removed (or to which access was disabled) is not infringing, or that you have the authorization from the copyright owner, the copyright owner's agent, or pursuant to the law, to post and use the content in your User Content, you may send a counter-notice containing the following information to the Copyright Agent:
                <ol type="i">
                    <li>Your physical or electronic signature;</li>
                    <li>Identification of the content that has been removed or to which access has been disabled and the location at which the content appeared before it was removed or disabled;</li>
                    <li>A statement that you have a good faith belief that the content was removed or disabled as a result of mistake or a misidentification of the content; and</li>
                    <li>Your name, address, telephone number, and e-mail address, a statement that you consent to the jurisdiction of the federal court in San Francisco, California, and a statement that you will accept service of process from the person who provided notification of the alleged infringement.</li>
                 </ol>
             </li>
             <li>Copy of Counter-Notice. If a counter-notice is received by the Copyright Agent, we may send a copy of the counter-notice to the original complaining party informing that person that we may replace the subject User Content or cease disabling it in 10 business days. Unless the copyright owner files an action seeking a court order against the registered user responsible for that User Content, that User Content may be replaced, or access to it restored, in 10 to 14 business days or more after receipt of the counter-notice, at our sole discretion.</li>
        </ol>
    </li>
    <li><h3><strong>Disclaimer of Warranties</strong></h3><br>
    THE SITE AND THE SITE SERVICES ARE PROVIDED "AS IS" AND WITHOUT WARRANTIES OF ANY KIND EITHER EXPRESS OR IMPLIED. TO THE FULLEST EXTENT PERMISSIBLE PURSUANT TO APPLICABLE LAW, Jockdrive DISCLAIMS ALL WARRANTIES, EXPRESS OR IMPLIED, INCLUDING, BUT NOT LIMITED TO, IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE. Jockdrive DOES NOT WARRANT THAT THE SITE OR SITE SERVICES WILL BE UNINTERRUPTED OR ERROR-FREE, THAT DEFECTS WILL BE CORRECTED, OR THAT THIS SITE OR THE SERVER THAT MAKES IT AVAILABLE ARE FREE OF VIRUSES OR OTHER HARMFUL COMPONENTS. Jockdrive DOES NOT WARRANT OR MAKE ANY REPRESENTATIONS REGARDING THE USE OR THE RESULTS OF THE USE OF THE SITE SERIVCES OR CONTENT IN THIS SITE IN TERMS OF THEIR CORRECTNESS, ACCURACY, RELIABILITY, OWNERSHIP, OR OTHERWISE. YOU (AND NOT Jockdrive) ASSUME THE ENTIRE COST OF ALL NECESSARY SERVICING, REPAIR, OR CORRECTION. APPLICABLE LAW MAY NOT ALLOW THE EXCLUSION OF IMPLIED WARRANTIES, SO THE ABOVE EXCLUSION MAY NOT APPLY TO YOU. 
    </li>
    <li><h3><strong>Limitation of Liability</strong></h3><br>
    UNDER NO CIRCUMSTANCES, INCLUDING, BUT NOT LIMITED TO, NEGLIGENCE, IS Jockdrive LIABLE FOR ANY SPECIAL, INDIRECT, INCIDENTAL, CONSEQUENTIAL OR EXEMPLARY DAMAGES THAT RESULT FROM THE USE OR THE INABILITY TO USE THE SITE, THE SITE SERVICES, OR ANY OTHER INTERACTIONS WITH Jockdrive, EVEN IF Jockdrive OR ANY Jockdrive AUTHORIZED REPRESENTATIVE HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES. APPLICABLE LAW MAY NOT ALLOW THE LIMITATION OR EXCLUSION OF LIABILITY OR INCIDENTAL OR CONSEQUENTIAL DAMAGES, SO THE ABOVE LIMITATION OR EXCLUSION MAY NOT APPLY TO YOU.  IN NO EVENT WILL JOCKDRIVE'S TOTAL LIABILITY TO YOU FOR ALL DAMAGES, LOSSES, AND CAUSES OF ACTION ARISING OUT OF OR RELATING TO THIS AGREEMENT OR YOUR USE OF THIS SITE (WHETHER IN CONTRACT, TORT, OR OTHERWISE) EXCEED THE AMOUNT PAID BY YOU, IF ANY, FOR ACCESSING THIS SITE DURING THE TWELVE (12) MONTHS PRECEDING YOUR CLAIM) OR ONE HUNDRED DOLLARS, WHICHEVER IS GREATER. 
    </li>
    <li><h3><strong>Indemnity</strong></h3><br>
    You agree to defend, indemnify, and hold Jockdrive and its employees, representatives, agents, attorneys, affiliates, directors, officers, managers, and shareholders (collectively, the "Indemnified Parties") harmless from any damage, lost, or expense (including attorneys' fees and costs) incurred in connection with any third-party claim, demand, or action ("Claim") brought or asserted against any of the Indemnified Parties: (i) alleging facts or circumstances that would constitute a breach of any provision of these Terms of Use by you; (ii) arising from or related to your use of the Site or the Site Services; or (iii) arising from or related to your User Content. You may not settle any Claim without the consent of Jockdrive. 
    </li>
    <li><h3><strong>General</strong></h3><br>
    The failure of Jockdrive to exercise or enforce any right or provision of these Terms of Use does not constitute a waiver of such right or provision. If any provision of these terms is held by a court of law to be unlawful, void, or for any reason unenforceable, then that provision will be deemed severable from these terms and will not affect the validity and enforceability of any remaining provisions. These Terms of Use and related guidelines may not be transferred or assigned by you but may be assigned by Jockdrive without restriction. This is the entire agreement between you and Jockdrive relating to the subject matter herein and may not be modified except in writing, signed by both parties, or by a change by Jockdrive to these Terms of Use posted on the Site. In order to cooperate with governmental requests, subpoenas or court orders, to protect Jockdrive's systems, or to ensure the integrity and operation of Jockdrive's business and systems, Jockdrive may access and disclose any information we consider necessary or appropriate, including, without limitation, Your Information, IP address and traffic information, usage history, and User Content you have published or uploaded through the Site Services. Jockdrive's right to disclose any such information supersedes any terms of the Privacy Policy. Jockdrive is not liable for any failure or unavailability of the Site as a result of acts of God, the deletion or corruption of storage media, power failures, natural phenomena, riots, acts of vandalism or computer hacking, acts or omissions of civil or military authority, war, terrorism or any other event beyond Jockdrive's control. Jockdrive may deliver notice to you under these Terms of Use by means of electronic mail, a general notice on the Site, or first class U.S. mail to your address on record in Jockdrive's account information. You may give notice to Jockdrive by first class U.S. mail or by recognized courier to the following address: [insert company address].
    </li>
</ol>

    </div>
</div>