<?php

$global = array(
    'adminEmail' => 'webmaster@example.com',
    'upload_path' => 'assets/',
    'gender' => array('male' => 'Male', 'female' => 'Female'),
    'payment_status' => array('transferred' => 'Transferred', 'cancelled' => 'Cancelled', 'pending' => 'Pending'),
    'gateway_payment_status' => array('complete' => 'Complete', 'pending' => 'Pending'), 
    'user_payment_status' => array('a' => 'Approved', 'p' => 'Pending', 'c' => 'Cancel'),
    'charge_type' => array('processing' => 'Processing','transaction' => 'Transaction'),
    'genre_for' => array('song' => 'Song','video' => 'Video'),
    'months' => array(
    				'1' => 'January',
    				'2' => 'February',
    				'3' => 'March',
    				'4' => 'April',
    				'5' => 'May',
    				'6' => 'June',
    				'7' => 'July',
    				'8' => 'August',
    				'9' => 'September',
    				'10' => 'October',
    				'11' => 'November',
    				'12' => 'December'
    				),
    'front_user_role' => 'fc1965dc-fc39-11e5-bac4-3c07717072c4',
    'admin_roles' => array('4eee73be-fb69-11e5-91d7-3c07717072c4' => 'Admin'),
    'plan_duration' => array('1d' => "1 Day",
                             '2d' => "2 Days",
                             '3d' => "3 Days",
                             '4d' => "4 Days",
                             '5d' => "5 Days",
                             '6d' => "6 Days",
                             '1w' => "1 Week",
                             '2w' => "2 Week",
                             '3w' => "3 Week",
                             '1m' => "1 Month",
                             '2m' => "2 Month",
                             '3m' => "3 Month",
                             '4m' => "4 Month",
                             '5m' => "5 Month",
                             '6m' => "6 Month",
                             '7m' => "7 Month",
                             '8m' => "8 Month",
                             '9m' => "9 Month",
                             '10m' => "10 Month",
                             '11m' => "11 Month",
                             '1y' => "1 Year",
                             '2y' => "2 Year",
                             '3y' => "3 Year",
                             '4y' => "4 Year",
                             '5y' => "5 Year"),
    'free_duration' => array('0d' => "0 Day",
                             '1d' => "1 Day",
                             '2d' => "2 Days",
                             '3d' => "3 Days",
                             '4d' => "4 Days",
                             '5d' => "5 Days",
                             '6d' => "6 Days",
                             '1w' => "1 Week",
                             '2w' => "2 Week",
                             '3w' => "3 Week",
                             '1m' => "1 Month",
                             '2m' => "2 Month",
                             '3m' => "3 Month",
                             '4m' => "4 Month",
                             '5m' => "5 Month",
                             '6m' => "6 Month",
                             '7m' => "7 Month",
                             '8m' => "8 Month",
                             '9m' => "9 Month",
                             '10m' => "10 Month",
                             '11m' => "11 Month",
                             '1y' => "1 Year",
                             '2y' => "2 Year",
                             '3y' => "3 Year",
                             '4y' => "4 Year",
                             '5y' => "5 Year"),
);
?>